# Consolidated Docker Compose for GS Crawler Stack
# Uses generic config-driven scrapers instead of individual containers

services:
  # === HEALTH MONITOR (unchanged) ===
  gs_health_monitor:
    build: ./docker_instances/000_health_monitor
    volumes:
      - ./httpdocs/crawler:/app/output
    ports:
      - "5015:5000"
    container_name: gs_health_monitor
    restart: unless-stopped

  # === GENERIC SCRAPER - Simple BeautifulSoup Crawlers ===
  # Replaces: 002_gz, 044_wiedelah, 041_immenrode, 048_jerstedt,
  #           051_vhs, 052_vhs_kinderuni
  gs_generic_scraper_simple:
    build: ./base_images/generic_scraper
    volumes:
      - ./httpdocs/crawler:/app/output
      - ./crawler_configs/simple:/app/configs
    container_name: gs_generic_scraper_simple
    restart: unless-stopped
    environment:
      - RUN_ON_START=true

  # === GENERIC SCRAPER - TschüssSchule Family ===
  # Replaces: 050_tschuessschule_studium, 053_tschuessschule_praktikum,
  #           054_tschuessschule_ausbildung
  gs_generic_scraper_tschuessschule:
    build: ./base_images/generic_scraper
    volumes:
      - ./httpdocs/crawler:/app/output
      - ./crawler_configs/tschuessschule:/app/configs
    container_name: gs_generic_scraper_tschuessschule
    restart: unless-stopped
    environment:
      - RUN_ON_START=true

  # === SPECIALIZED CRAWLERS (keep separate for now) ===

  # PHP API Fetcher - unique runtime
  gs_compiler_002_fepa:
    build: ./docker_instances/002_ferienpass
    volumes:
      - ./httpdocs/crawler:/app/output
    container_name: gs_compiler_002_fepa
    restart: unless-stopped

  # Selenium-based crawlers (browser automation required)
  gs_compiler_045_naturgefahren:
    build: ./docker_instances/045_naturgefahren
    volumes:
      - ./httpdocs/crawler:/app/output
    container_name: gs_compiler_045_naturgefahren
    restart: unless-stopped

  gs_compiler_035_talsperren:
    build: ./docker_instances/035_talsperren
    volumes:
      - ./httpdocs/crawler:/app/output
    container_name: gs_compiler_035_talsperren
    restart: unless-stopped

  # Image/GIF generation crawlers (specialized PIL/matplotlib processing)
  gs_compiler_032_webcams_goslar:
    build: ./docker_instances/032_webcams_goslar
    volumes:
      - ./httpdocs/crawler:/app/output
    container_name: gs_compiler_032_webcams_goslar
    restart: unless-stopped

  gs_compiler_033_goslar24-7:
    build: ./docker_instances/033_goslar24-7
    volumes:
      - ./httpdocs/crawler:/app/output
    container_name: gs_compiler_033_goslar_24-7
    restart: unless-stopped

  gs_compiler_047_bodenwasser:
    build: ./docker_instances/047_bodenwasser
    volumes:
      - ./httpdocs/crawler:/app/output
    container_name: gs_compiler_047_bodenwasser
    restart: unless-stopped

  # XML/RSS generation
  gs_compiler_001_senioren:
    build: ./docker_instances/001_senioren
    volumes:
      - ./httpdocs/crawler:/app/output
    container_name: gs_compiler_001_senioren
    restart: unless-stopped

  # Flask event API (stateful)
  gs_compiler_068_altstadtfest:
    build: ./docker_instances/068_altstadtfest
    volumes:
      - ./httpdocs/crawler:/app/output
    ports:
      - "5016:5000"
    container_name: gs_compiler_068_altstadtfest
    restart: unless-stopped

  # High-frequency crawler (every 3 min - keep separate for scheduling)
  gs_compiler_019_was_app:
    build: ./docker_instances/019_was_app
    volumes:
      - ./httpdocs/crawler:/app/output
    container_name: gs_compiler_019_was_app
    restart: unless-stopped

# Shared volume for all output files
volumes:
  crawler_output:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./httpdocs/crawler
