
services:
  # gs_health_monitor:
  #   build: ./docker_instances/000_health_monitor
  #   volumes:
  #     - ./httpdocs/crawler:/app/output
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   ports:
  #     - "5000:5000"
  #   container_name: gs_health_monitor
  #   depends_on:
  #     - gs_compiler_001_senioren
  #     - gs_compiler_002_fepa
  #     - gs_compiler_040_hp
  #     - gs_compiler_019_was_app
  #     - gs_compiler_041_immenrode
  #     - gs_compiler_042_freiwilligen
  #     - gs_compiler_044_wiedelah
  #     - gs_compiler_045_naturgefahren
  #     - gs_compiler_047_bodenwasser
  #     - gs_compiler_048_jerstedt
  #     - gs_compiler_002_gz
  gs_compiler_001_senioren:
    build: ./docker_instances/001_senioren
    volumes:
      - ./httpdocs/crawler:/app/output
    container_name: gs_compiler_001_senioren
  gs_compiler_002_fepa:
    build: ./docker_instances/002_ferienpass
    volumes:
      - ./httpdocs/crawler:/app/output
    container_name: gs_compiler_002_fepa
  gs_compiler_040_hp:
    build: ./docker_instances/040_hp
    volumes:
      - ./httpdocs/crawler:/app/output
    container_name: gs_compiler_040_hp
  gs_compiler_019_was_app:
    build: ./docker_instances/019_was_app
    volumes:
      - ./httpdocs/crawler:/app/output
    container_name: gs_compiler_019_was_app
  gs_compiler_041_immenrode:
    build: ./docker_instances/041_immenrode
    volumes:
      - ./httpdocs/crawler:/app/output
    container_name: gs_compiler_041_immenrode
  gs_compiler_042_freiwilligen:
    build: ./docker_instances/042_freiwilligen
    volumes:
      - ./httpdocs/crawler:/app/output
    container_name: gs_compiler_042_freiwilligen
  gs_compiler_044_wiedelah:
    build: ./docker_instances/044_wiedelah
    volumes:
      - ./httpdocs/crawler:/app/output
    container_name: gs_compiler_044_wiedelah
  gs_compiler_045_naturgefahren:
    build: ./docker_instances/045_naturgefahren
    volumes:
      - ./httpdocs/crawler:/app/output
    container_name: gs_compiler_045_naturgefahren
  gs_compiler_047_bodenwasser:
    build: ./docker_instances/047_bodenwasser
    volumes:
      - ./httpdocs/crawler:/app/output
    container_name: gs_compiler_047_bodenwasser
  gs_compiler_048_jerstedt:
    build: ./docker_instances/048_jerstedt
    volumes:
      - ./httpdocs/crawler:/app/output
    container_name: gs_compiler_048_jerstedt
  gs_compiler_002_gz:
    build: ./docker_instances/002_gz
    volumes:
      - ./httpdocs/crawler:/app/output
    container_name: gs_compiler_002_gz
  gs_compiler_053_tschuessschule_praktikum:
    build: ./docker_instances/053_tschuessschule_praktikum
    volumes:
      - ./httpdocs/crawler:/app/output
    container_name: gs_compiler_053_tschuessschule_praktikum
  gs_compiler_054_tschuessschule_ausbildung:
    build: ./docker_instances/054_tschuessschule_ausbildung
    volumes:
      - ./httpdocs/crawler:/app/output
    container_name: gs_compiler_054_tschuessschule_ausbildung
  gs_compiler_050_tschuessschule_studium:
    build: ./docker_instances/050_tschuessschule_studium
    volumes:
      - ./httpdocs/crawler:/app/output
    container_name: gs_compiler_050_tschuessschule_studium
  gs_compiler_014_kunst_in_ar:
    build: ./docker_instances/014_kunst_in_ar
    volumes:
      - ./httpdocs/crawler:/app/output
    container_name: gs_compiler_014_kunst_in_ar
  gs_compiler_051_vhs:
    build: ./docker_instances/051_vhs
    volumes:
      - ./httpdocs/crawler:/app/output
    container_name: gs_compiler_051_vhs
  gs_compiler_052_vhs_kinderuni:
    build: ./docker_instances/052_vhs_kinderuni
    volumes:
      - ./httpdocs/crawler:/app/output
    container_name: gs_compiler_052_vhs_kinderuni
  gs_compiler_031_goslarer_geschichten:
    build: ./docker_instances/031_goslarer_geschichten
    volumes:
      - ./httpdocs/crawler:/app/output
    container_name: gs_compiler_031_goslarer_geschichten
  gs_compiler_035_talsperren:
    build: ./docker_instances/035_talsperren
    volumes:
      - ./httpdocs/crawler:/app/output
    container_name: gs_compiler_035_talsperren
  gs_compiler_056_serviceportal:
    build: ./docker_instances/056_serviceportal
    volumes:
      - ./httpdocs/crawler:/app/output
    container_name: gs_compiler_056_serviceportal
  gs_compiler_027_erster_freitag:
    build: ./docker_instances/027_erster_freitag
    volumes:
      - ./httpdocs/crawler:/app/output
    container_name: gs_compiler_027_erster_freitag
  gs_compiler_032_webcams_goslar:
    build: ./docker_instances/032_webcams_goslar
    volumes:
      - ./httpdocs/crawler:/app/output
    container_name: gs_compiler_032_webcams_goslar