
# Production Docker Compose für GS Crawler Stack
# Verwendet pre-built Images aus GitHub Container Registry

services:
  # === HEALTH MONITOR ===
  gs_health_monitor:
    image: ghcr.io/machmitgoslar/gs_crawler_000_health_monitor:latest
    volumes:
      - ./httpdocs/crawler:/app/output
    ports:
      - "5015:5000"
    container_name: gs_health_monitor
    restart: unless-stopped
    depends_on:
      - gs_compiler_001_senioren
      - gs_compiler_002_fepa
      - gs_compiler_002_gz

  # === NEWS & MEDIA CRAWLER ===
  gs_compiler_001_senioren:
    image: ghcr.io/machmitgoslar/gs_crawler_001_senioren:latest
    volumes:
      - ./httpdocs/crawler:/app/output
    container_name: gs_compiler_001_senioren
    restart: unless-stopped

  gs_compiler_002_gz:
    image: ghcr.io/machmitgoslar/gs_crawler_002_gz:latest
    volumes:
      - ./httpdocs/crawler:/app/output
    container_name: gs_compiler_002_gz
    restart: unless-stopped

  gs_compiler_040_hp:
    image: ghcr.io/machmitgoslar/gs_crawler_040_hp:latest
    volumes:
      - ./httpdocs/crawler:/app/output
    container_name: gs_compiler_040_hp
    restart: unless-stopped

  # === EVENT CRAWLER ===
  gs_compiler_002_fepa:
    image: ghcr.io/machmitgoslar/gs_crawler_002_ferienpass:latest
    volumes:
      - ./httpdocs/crawler:/app/output
    container_name: gs_compiler_002_fepa
    restart: unless-stopped

  gs_compiler_019_was_app:
    image: ghcr.io/machmitgoslar/gs_crawler_019_was_app:latest
    volumes:
      - ./httpdocs/crawler:/app/output
    container_name: gs_compiler_019_was_app
    restart: unless-stopped

  gs_compiler_027_erster_freitag:
    image: ghcr.io/machmitgoslar/gs_crawler_027_erster_freitag:latest
    volumes:
      - ./httpdocs/crawler:/app/output
    container_name: gs_compiler_027_erster_freitag
    restart: unless-stopped

  # === LOCAL NEWS CRAWLER ===
  gs_compiler_041_immenrode:
    image: ghcr.io/machmitgoslar/gs_crawler_041_immenrode:latest
    volumes:
      - ./httpdocs/crawler:/app/output
    container_name: gs_compiler_041_immenrode
    restart: unless-stopped

  gs_compiler_048_jerstedt:
    image: ghcr.io/machmitgoslar/gs_crawler_048_jerstedt:latest
    volumes:
      - ./httpdocs/crawler:/app/output
    container_name: gs_compiler_048_jerstedt
    restart: unless-stopped

  # === COMMUNITY & VOLUNTEER CRAWLER ===
  gs_compiler_042_freiwilligen:
    image: ghcr.io/machmitgoslar/gs_crawler_042_freiwilligen:latest
    volumes:
      - ./httpdocs/crawler:/app/output
    container_name: gs_compiler_042_freiwilligen
    restart: unless-stopped

  gs_compiler_044_wiedelah:
    image: ghcr.io/machmitgoslar/gs_crawler_044_wiedelah:latest
    volumes:
      - ./httpdocs/crawler:/app/output
    container_name: gs_compiler_044_wiedelah
    restart: unless-stopped

  gs_compiler_031_goslarer_geschichten:
    image: ghcr.io/machmitgoslar/gs_crawler_031_goslarer_geschichten:latest
    volumes:
      - ./httpdocs/crawler:/app/output
    container_name: gs_compiler_031_goslarer_geschichten
    restart: unless-stopped

  # === ENVIRONMENTAL MONITORING ===
  gs_compiler_045_naturgefahren:
    image: ghcr.io/machmitgoslar/gs_crawler_045_naturgefahren:latest
    volumes:
      - ./httpdocs/crawler:/app/output
    container_name: gs_compiler_045_naturgefahren
    restart: unless-stopped

  gs_compiler_047_bodenwasser:
    image: ghcr.io/machmitgoslar/gs_crawler_047_bodenwasser:latest
    volumes:
      - ./httpdocs/crawler:/app/output
    container_name: gs_compiler_047_bodenwasser
    restart: unless-stopped

  gs_compiler_035_talsperren:
    image: ghcr.io/machmitgoslar/gs_crawler_035_talsperren:latest
    volumes:
      - ./httpdocs/crawler:/app/output
    container_name: gs_compiler_035_talsperren
    restart: unless-stopped

  # === EDUCATION CRAWLER ===
  gs_compiler_050_tschuessschule_studium:
    image: ghcr.io/machmitgoslar/gs_crawler_050_tschuessschule_studium:latest
    volumes:
      - ./httpdocs/crawler:/app/output
    container_name: gs_compiler_050_tschuessschule_studium
    restart: unless-stopped

  gs_compiler_051_vhs:
    image: ghcr.io/machmitgoslar/gs_crawler_051_vhs:latest
    volumes:
      - ./httpdocs/crawler:/app/output
    container_name: gs_compiler_051_vhs
    restart: unless-stopped

  gs_compiler_052_vhs_kinderuni:
    image: ghcr.io/machmitgoslar/gs_crawler_052_vhs_kinderuni:latest
    volumes:
      - ./httpdocs/crawler:/app/output
    container_name: gs_compiler_052_vhs_kinderuni
    restart: unless-stopped

  gs_compiler_053_tschuessschule_praktikum:
    image: ghcr.io/machmitgoslar/gs_crawler_053_tschuessschule_praktikum:latest
    volumes:
      - ./httpdocs/crawler:/app/output
    container_name: gs_compiler_053_tschuessschule_praktikum
    restart: unless-stopped

  gs_compiler_054_tschuessschule_ausbildung:
    image: ghcr.io/machmitgoslar/gs_crawler_054_tschuessschule_ausbildung:latest
    volumes:
      - ./httpdocs/crawler:/app/output
    container_name: gs_compiler_054_tschuessschule_ausbildung
    restart: unless-stopped

  # === SPECIALIZED CRAWLER ===
  gs_compiler_014_kunst_in_ar:
    image: ghcr.io/machmitgoslar/gs_crawler_014_kunst_in_ar:latest
    volumes:
      - ./httpdocs/crawler:/app/output
    container_name: gs_compiler_014_kunst_in_ar
    restart: unless-stopped

  gs_compiler_032_webcams_goslar:
    image: ghcr.io/machmitgoslar/gs_crawler_032_webcams_goslar:latest
    volumes:
      - ./httpdocs/crawler:/app/output
    container_name: gs_compiler_032_webcams_goslar
    restart: unless-stopped

  gs_compiler_033_goslar24-7:
    image: ghcr.io/machmitgoslar/gs_crawler_033_goslar24-7:latest
    volumes:
      - ./httpdocs/crawler:/app/output
    container_name: gs_compiler_033_goslar24-7
    restart: unless-stopped

  gs_compiler_056_serviceportal:
    image: ghcr.io/machmitgoslar/gs_crawler_056_serviceportal:latest
    volumes:
      - ./httpdocs/crawler:/app/output
    container_name: gs_compiler_056_serviceportal
    restart: unless-stopped

# Gemeinsames Volume für alle Output-Dateien
volumes:
  crawler_output:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./httpdocs/crawler
